name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'yarn'
      - run: pwd
      - run: yarn install
      - run: yarn build

      # Upload dist file to the release as an asset.
      - name: Upload dist files to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/lovelace-full-icons/lovelace-full-icons/dist/full-icons.js
          overwrite: true

      # Validate the release
      - name: HACS Validation
        uses: "hacs/action@main"
        with:
          category: "plugin"

